


GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/5feec040800cee09dcf4db1f

###
DELETE http://localhost:3001/api/persons/5ff0ec88f76ecf0f18b02628

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "F",
    "number": "5576"
}