GET https://frozen-crag-67747.herokuapp.com/api/persons

###
GET https://frozen-crag-67747.herokuapp.com/api/persons/2

###
DELETE https://frozen-crag-67747.herokuapp.com/api/persons/5

###
POST https://frozen-crag-67747.herokuapp.com/api/persons/
Content-Type: application/json

{
    "name": "Markduk",
    "number": "12312"
}