


GET https://frozen-crag-67747.herokuapp.com/api/persons

###
GET https://frozen-crag-67747.herokuapp.com/api/persons/5ff1011bef2d1370c0c34e62

###
DELETE https://frozen-crag-67747.herokuapp.com/api/persons/5ff2268d39d011001764ce54

###
POST https://frozen-crag-67747.herokuapp.com/api/persons/
Content-Type: application/json

{
    "name": "nonuma",
    "number": "5576323456546"
}

###
PUT https://frozen-crag-67747.herokuapp.com/api/persons/5ff228982e3f160017667d0b
Content-Type: application/json

{
    "name": "yrq",
    "number": "33333333"
}